<?php /*	
=========================================================================================	
|	PÁGINA DE CONSULTA DE FICHA DO CADASTRO
|   EXIBE UM REGISTRO PARA CONSULTA OU EXCLUSÃO
=========================================================================================	
*/ 

	$FW_tabela = "clientes";	
	if ($view_tipo == '1' ) {
		echo "<H1>CONSULTANDO REGISTRO</H1>";
	} else if ($view_tipo == '2') { 
		echo "<H1>EXCLUIR REGISTRO</H1>";
	}
	
	// VETOR COM OS NOMES DAS COLUNAS DA TABELA E OS RESPECTIVOS CAMPOS
	global $start;
	include_once(FW_PATH_SERV . FW_RAIZ. FW_VIEWS . $start->_controller ."/blocks/cabCampo.php");	//	INCLUI O ARQUIVO COM CABEÇALHOS E CAMPOS
		
	// PARA EXCLUIR ALGUM CAMPO DA VISUALIZAÇÃO USE:
	$excluir = array();
	// $excluir = array("id","email","cpf");
	$FW_cab = $start->ExcluirCampo($FW_campos, $excluir );
		
	include_once(FW_PATH_SERV . FW_SCAF_BLOCKS . "scafTableRegShow.php");							//	CHAMA O BLOCO DE CÓDIGO QUE MOSTRA O REGISTRO
	include_once(FW_PATH_SERV . FW_SCAF_BLOCKS . "scafBotaoConfirmaConsultaExclusao.php");			//	BOTAO CONFIRMA CONSULTA EXCLUSAO
?>