<?php /*	
==========================================================================	
|	PÁGINA DE INCLUIR OU ALTERAR UMA FICHA DO CADASTRO
==========================================================================	
*/
	if ($view_tipo == '1') {						//	INCLUSAO
		echo "<H1>INCLUIR REGISTRO</H1>";
		$FW_operacao =  $view_redir . "incluir/"; 		//	VALOR PARA SETAR OPERACAO A SER FEITA...
	
	} else if ($view_tipo == '2') {					//	ALTERACAO
		echo "<H1>ALTERAR REGISTRO</H1>";		
		$FW_operacao =  $view_redir . "alterar/id/".$view_show_registro[0]['id']."/"; 		//	VALOR PARA SETAR OPERACAO A SER FEITA...
	}	
	
	include("forms/formulario.php");				//	FORMULARIO DE ENTRADA DE DADOS
?>